// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// cmaesOptim
NumericVector cmaesOptim(const NumericVector x0, const NumericVector sigma, Function optimFun, Function optimFunBlock, NumericVector lowerB, NumericVector upperB, int cmaAlgo, int lambda, int maxEvals, double xtol, double ftol);
RcppExport SEXP Rlibcmaes_cmaesOptim(SEXP x0SEXP, SEXP sigmaSEXP, SEXP optimFunSEXP, SEXP optimFunBlockSEXP, SEXP lowerBSEXP, SEXP upperBSEXP, SEXP cmaAlgoSEXP, SEXP lambdaSEXP, SEXP maxEvalsSEXP, SEXP xtolSEXP, SEXP ftolSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericVector >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< Function >::type optimFun(optimFunSEXP);
    Rcpp::traits::input_parameter< Function >::type optimFunBlock(optimFunBlockSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lowerB(lowerBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type upperB(upperBSEXP);
    Rcpp::traits::input_parameter< int >::type cmaAlgo(cmaAlgoSEXP);
    Rcpp::traits::input_parameter< int >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type maxEvals(maxEvalsSEXP);
    Rcpp::traits::input_parameter< double >::type xtol(xtolSEXP);
    Rcpp::traits::input_parameter< double >::type ftol(ftolSEXP);
    __result = Rcpp::wrap(cmaesOptim(x0, sigma, optimFun, optimFunBlock, lowerB, upperB, cmaAlgo, lambda, maxEvals, xtol, ftol));
    return __result;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP Rlibcmaes_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello_world());
    return __result;
END_RCPP
}
