# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcpp function that calls the libcmaes library
#' @param x0 The initial start vector
#' @param sigma The initial standard deviation
#' @param optimFun The original R function
#' @param optimFunBlock The 'block' version of the R function (given multiple vectors returns a vector of fitness values)
#' @param lowerB Lower bound vector
#' @param upperB Upper bound vector
#' @param cmaAlgo Integer, determining the cma-es algorithm to run
#' @param lambda The initial population size
#' @param maxEvals The maximum number of function calls to allow
#' @param xtol The x-convergence tolerance
#' @param ftol The function value convergence tolerance
#' @param traceFreq How often should we print out optimization iterations
#' @param seed The random seed
#' @param quietRun Should we print optimizer outputs during the optimization process
#' @export
cmaesOptim <- function(x0, sigma, optimFun, optimFunBlock, lowerB, upperB, cmaAlgo, lambda = -1L, maxEvals = 1e3L, xtol = 1e-12, ftol = 1e-12, traceFreq = 1L, seed = 0L, quietRun = FALSE) {
    .Call('Rlibcmaes_cmaesOptim', PACKAGE = 'Rlibcmaes', x0, sigma, optimFun, optimFunBlock, lowerB, upperB, cmaAlgo, lambda, maxEvals, xtol, ftol, traceFreq, seed, quietRun)
}

rcpp_hello_world <- function() {
    .Call('Rlibcmaes_rcpp_hello_world', PACKAGE = 'Rlibcmaes')
}

