# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cmaesOptim <- function(x0, sigma, optimFun, optimFunBlock, lowerB, upperB, cmaAlgo, lambda = -1L, maxEvals = 1e3L, xtol = 1e-12, ftol = 1e-12, traceFreq = 1L) {
    .Call('Rlibcmaes_cmaesOptim', PACKAGE = 'Rlibcmaes', x0, sigma, optimFun, optimFunBlock, lowerB, upperB, cmaAlgo, lambda, maxEvals, xtol, ftol, traceFreq)
}

rcpp_hello_world <- function() {
    .Call('Rlibcmaes_rcpp_hello_world', PACKAGE = 'Rlibcmaes')
}

