# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cmaesOptim <- function(x0, sigma, optimFun, lowerB, upperB, maxevals = 1e3L) {
    .Call('Rlibcmaes_cmaesOptim', PACKAGE = 'Rlibcmaes', x0, sigma, optimFun, lowerB, upperB, maxevals)
}

rcpp_hello_world <- function() {
    .Call('Rlibcmaes_rcpp_hello_world', PACKAGE = 'Rlibcmaes')
}

